apiVersion: apps/v1
kind: Deployment
metadata:
  name: humix-user-api
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: humix-user-api
  template:
    metadata:
      labels:
        app: humix-user-api
    spec:
      containers:
      - name: humix-user-api
        image: humix-user-api
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_Bwz1aQ6KHntS@ep-hidden-cloud-a8efcee1-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"