apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: user

images:
- name: humix-user-api
  newName: blgianinis/humix-user-api
  newTag: 85370cc8994b810c1144145f5fc6c703e7fbeb9c
